collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1860503270290792
  brandStrength: 0.8458781
  lightness: 0.9850400621071458
  brandColors:
    - '#0B0B0B'
    - '#F8FEFC'
    - '#BC9F9B'
    - '#BFD7D4'
    - '#016965'
  rhythmicContrast: 0.4848648018669337
typography_spectrum: 0.2365591
layout_spectrum: 0.2849462
name: fustrated fly fisherman
